### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [NaotoNTP/Prism-Paradise#1]
whenever i tried to build the game, these errors come up

SN 68k version 2.53

C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\ENGINE\MACROS.ASM(134) : Error : Op-code not recognised
smps_id function ptr,((ptr-offset)/ptrsize+idstart)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(5) : Error : Op-code not recognised
offset := musicindex
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(6) : Error : Op-code not recognised
ptrsize := 4
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(7) : Error : Op-code not recognised
idstart := 1
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(11) : Error : Unexpected characters at end of line
musid_2presult = smps_id(ptr_mus81)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(12) : Error : Unexpected characters at end of line
musid_ehz = smps_id(ptr_mus82)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(13) : Error : Unexpected characters at end of line
musid_mcz_2p = smps_id(ptr_mus83)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(14) : Error : Unexpected characters at end of line
musid_ooz = smps_id(ptr_mus84)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(15) : Error : Unexpected characters at end of line
musid_mtz = smps_id(ptr_mus85)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(16) : Error : Unexpected characters at end of line
musid_htz = smps_id(ptr_mus86)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(17) : Error : Unexpected characters at end of line
musid_arz = smps_id(ptr_mus87)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(18) : Error : Unexpected characters at end of line
musid_cnz_2p = smps_id(ptr_mus88)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(19) : Error : Unexpected characters at end of line
musid_cnz = smps_id(ptr_mus89)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(20) : Error : Unexpected characters at end of line
musid_dez = smps_id(ptr_mus8a)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(21) : Error : Unexpected characters at end of line
musid_mcz = smps_id(ptr_mus8b)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(22) : Error : Unexpected characters at end of line
musid_ehz_2p = smps_id(ptr_mus8c)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(23) : Error : Unexpected characters at end of line
musid_scz = smps_id(ptr_mus8d)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(24) : Error : Unexpected characters at end of line
musid_cpz = smps_id(ptr_mus8e)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(25) : Error : Unexpected characters at end of line
musid_wfz = smps_id(ptr_mus8f)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(26) : Error : Unexpected characters at end of line
musid_hpz = smps_id(ptr_mus90)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(27) : Error : Unexpected characters at end of line
musid_options = smps_id(ptr_mus91)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(28) : Error : Unexpected characters at end of line
musid_specstage = smps_id(ptr_mus92)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(29) : Error : Unexpected characters at end of line
musid_boss = smps_id(ptr_mus93)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(30) : Error : Unexpected characters at end of line
musid_endboss = smps_id(ptr_mus94)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(31) : Error : Unexpected characters at end of line
musid_ending = smps_id(ptr_mus95)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(32) : Error : Unexpected characters at end of line
musid_supersonic = smps_id(ptr_mus96)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(33) : Error : Unexpected characters at end of line
musid_invincible = smps_id(ptr_mus97)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(34) : Error : Unexpected characters at end of line
musid_extralife = smps_id(ptr_mus98)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(35) : Error : Unexpected characters at end of line
musid_title = smps_id(ptr_mus99)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(36) : Error : Unexpected characters at end of line
musid_endlevel = smps_id(ptr_mus9a)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(37) : Error : Unexpected characters at end of line
musid_gameover = smps_id(ptr_mus9b)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(38) : Error : Unexpected characters at end of line
musid_continue = smps_id(ptr_mus9c)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(39) : Error : Unexpected characters at end of line
musid_emerald = smps_id(ptr_mus9d)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(40) : Error : Unexpected characters at end of line
musid_credits = smps_id(ptr_mus9e)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(41) : Error : Unexpected characters at end of line
musid_countdown = smps_id(ptr_mus9f)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(42) : Error : Unexpected characters at end of line
musid__end = smps_id(ptr_musend)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(45) : Error : Op-code not recognised
offset := soundindex
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(46) : Error : Op-code not recognised
ptrsize := 4
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(47) : Error : Op-code not recognised
idstart := $40
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(50) : Error : Unexpected characters at end of line
sndid_jump = smps_id(ptr_snda0)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(51) : Error : Unexpected characters at end of line
sndid_checkpoint = smps_id(ptr_snda1)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(52) : Error : Unexpected characters at end of line
sndid_spikeswitch = smps_id(ptr_snda2)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(53) : Error : Unexpected characters at end of line
sndid_hurt = smps_id(ptr_snda3)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(54) : Error : Unexpected characters at end of line
sndid_skidding = smps_id(ptr_snda4)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(55) : Error : Unexpected characters at end of line
sndid_blockpush = smps_id(ptr_snda5)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(56) : Error : Unexpected characters at end of line
sndid_hurtbyspikes = smps_id(ptr_snda6)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(57) : Error : Unexpected characters at end of line
sndid_sparkle = smps_id(ptr_snda7)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(58) : Error : Unexpected characters at end of line
sndid_beep = smps_id(ptr_snda8)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(59) : Error : Unexpected characters at end of line
sndid_ssitem = smps_id(ptr_snda9)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(60) : Error : Unexpected characters at end of line
sndid_splash = smps_id(ptr_sndaa)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(61) : Error : Unexpected characters at end of line
sndid_swish = smps_id(ptr_sndab)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(62) : Error : Unexpected characters at end of line
sndid_bosshit = smps_id(ptr_sndac)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(63) : Error : Unexpected characters at end of line
sndid_inhalingbubble = smps_id(ptr_sndad)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(64) : Error : Unexpected characters at end of line
sndid_arrowfiring = smps_id(ptr_sndae)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(65) : Error : Unexpected characters at end of line
sndid_lavaball = smps_id(ptr_sndae)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(66) : Error : Unexpected characters at end of line
sndid_shield = smps_id(ptr_sndaf)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(67) : Error : Unexpected characters at end of line
sndid_laserbeam = smps_id(ptr_sndb0)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(68) : Error : Unexpected characters at end of line
sndid_electric = smps_id(ptr_sndb1)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(69) : Error : Unexpected characters at end of line
sndid_drown = smps_id(ptr_sndb2)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(70) : Error : Unexpected characters at end of line
sndid_fireburn = smps_id(ptr_sndb3)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(71) : Error : Unexpected characters at end of line
sndid_bumper = smps_id(ptr_sndb4)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(72) : Error : Unexpected characters at end of line
sndid_ring = smps_id(ptr_sndb5)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(73) : Error : Unexpected characters at end of line
sndid_ringright = smps_id(ptr_sndb5)
C:\USERS\DELL USER\DESKTOP\HEDGEBREW-MAIN\SOUND\SOUND IDS.ASM(74) : Error : Unexpected characters at end of line
sndid_spikesmove = smps_id(ptr_sndb6)

Too many errors, assembler aborting...
Errors during pass 1 - pass 2 aborted
Assembly completed.
64 error(s) from 2238 lines in 0.0 seconds

help?

**Comment by NaotoNTP** [comment]
Hello there! My apologies; I had been in the process of adding a sound driver to the project and figured I could get away with resolving errors over the course of several commits. I hadn't realized anyone was playing with this yet as it's not really ready for release. For now, I've reverted the sound driver commit and will probably keep any sound driver development off of the main branch until it's error-free. It should build now without any issues.

**Comment by CHUCKECHEESETubeYT** [comment]
ok, thx man
